apiVersion: v1
kind: Pod
metadata:
  name: flask-test
  namespace: flask
  labels:
    app: flask-test
spec:
  containers:
  - name: flask-test
    image: acracrmauritsafyz.azurecr.io/flask-test:version2
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    readinessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
