apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-test
    namespace: flask
  name: flask
  namespace: flask
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-test
  sessionAffinity: None
  type: LoadBalancer
