apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-21T06:31:44Z"
  labels:
    app: flask-test
  name: flask-pod
  namespace: flask
spec:
  clusterIP: 172.20.220.243
  clusterIPs:
  - 172.20.220.243
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-test
  sessionAffinity: None
  type: LoadBalancer
